export const NOTES_LIST_REQUEST = "NOTE_LIST_REQUEST";
export const NOTES_LIST_SUCSESS = "NOTE_LIST_SUCSESS";
export const NOTES_LIST_FAIL = "NOTE_LIST_FAIL";

export const NOTES_CREATE_REQUEST = "NOTES_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTES_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL = "NOTES_CREATE_FAIL";
